### ISSUE TITLE
GameID only supports a finite amount of games

### ISSUE THREAD

**Issue by tripledubs** [seankelly55/tictactoe#2]

**Comment by tripledubs** [comment]
If the GameID uses only 2 random bytes, I think the probability of duplicate $gameid being generated reaches 50% after only 300 games. 

1 - [ 2**16 / 2**16 X ( (2**16-1) / 2**16) X ( (2**16 -2) / 2**16)... (( 2**16-300) / 2**16) ] > .5

http://en.wikipedia.org/wiki/Birthday_problem

**Comment by seankelly55** [comment]
I've solved this problem by adding a trigger for auto incrementing the id, all game ids are now integers. There may be a security concern because a user could predict the game ids and auto join new games thus causing a denial of service. This could be solved with using captcha but for our class I dont think its a problem.
